name: WeeklyPlanner
options:
  bundleIdPrefix: com.jonathanprocter
  deploymentTarget:
    iOS: "16.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

schemes:
  WeeklyPlanner:
    build:
      targets:
        WeeklyPlanner: all
    test:
      targets:
        - WeeklyPlannerTests

settings:
  base:
    SWIFT_VERSION: "5.9"
    TARGETED_DEVICE_FAMILY: "1,2"
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"

targets:
  WeeklyPlanner:
    type: application
    platform: iOS
    sources:
      - path: WeeklyPlanner
        excludes:
          - "**/*.plist"
    settings:
      base:
        INFOPLIST_FILE: WeeklyPlanner/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.jonathanprocter.weeklyplanner
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: N866QDJBQX
    info:
      path: WeeklyPlanner/Info.plist
      properties:
        CFBundleDisplayName: Weekly Planner
        CFBundleName: Weekly Planner
        CFBundleShortVersionString: "1.0"
        CFBundleVersion: "1"
        UILaunchScreen:
          UIColorName: ""
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        CFBundleURLTypes:
          - CFBundleURLName: "Google OAuth"
            CFBundleURLSchemes:
              - "com.jonathanprocter.weeklyplanner"
        NSMicrophoneUsageDescription: "Weekly Planner needs microphone access to record voice notes during client sessions."
        NSSpeechRecognitionUsageDescription: "Weekly Planner uses speech recognition to transcribe your voice notes into text."

  WeeklyPlannerTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: WeeklyPlannerTests
    dependencies:
      - target: WeeklyPlanner
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
